### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by caioopr** [caioopr/second_brain#1]
- [ ] rewrite using TypeScript
- [x] add filter posts by tag Component
- [ ] add a "Folders" Page (like playlists)
- [x] add a "Projects" Page
